### ISSUE TITLE
Invisible, inviolate screen objects

### ISSUE THREAD

**Issue by xenoflot** [McJty/RFTools#195] opened 2015-06-01 12:51 UTC
Hi McJty,

RFT 2.93... I placed some screens tonight to experiment. Started whacking them with a wrench (variously crescent hammer and yeta) and found they went invis then changed size. Then started shift-whacking and some started popping, then I discovered that 4 screens have become invisible entities. No texture, just the screen's hitbox. No response to any kind of interaction with hands, wrenches or picks.

Not sure exactly which combination of actions resulted in this state but it was nothing more than a wrench and a shift key.

**Comment by McJty** [comment] 2015-06-01 12:52
That's normal. These screens have an invisible mode (if you put modules in it then you can see the contents). This is intended for floating text.

So not a bug and intended behaviour.

**Comment by xenoflot** [comment] 2015-06-01 22:49
I don't think it's normal that they won't respond to any kind of interaction. IE can't break the block with a pick nor wrench. Can't open a GUI.

**Comment by McJty** [comment] 2015-06-02 03:16
Hmm. I can interact with them just fine. Can you describe to me exactly what you did then so that I can perhaps reproduce this? This is not in creative is it?

**Comment by McJty** [comment] 2015-06-02 04:08
Never mind, found out how to reproduce it.

**Comment by McJty** [comment] 2015-06-02 09:14
Fixed in next release

**Closed by McJty** 2015-06-02 09:14 UTC
