### ISSUE TITLE
1.9 Shield projector can only toggle on/off the template but cannot actually make it work

### ISSUE THREAD

**Issue by LordHellscream** [McJty/RFTools#481] opened 2016-03-24 07:18 UTC
Minecraft 1.9
Forge 1802

I can right click using wrench to turn on/off the template, but the template kept showing as the template look, in addition, the rules for passing through does not work. the template is solid and it remain solid after toggle on the projector. The projector is fully powered.

**Comment by McJty** [comment] 2016-03-24 07:29
Once I finish porting Deep Resonance I will look over the 1.9 issues for RFTools. Thanks for reporting

**Comment by McJty** [comment] 2016-03-24 08:02
I cannot reproduce this. Exactly how are you doing this? The shield templates are adjacent to the shield projector? You right click the projector with the wrench? For me it works fine

**Comment by LordHellscream** [comment] 2016-03-24 20:09
Which version of Forge are you using? I heard they have a few changes they may have broken things? may be the version we are using are different?

**Comment by McJty** [comment] 2016-03-25 04:13
Can  you try if you can also reproduce this with the latest version of rftools? I didn't change anything but I did upgrade forge in my dev environment.

**Comment by LordHellscream** [comment] 2016-03-25 08:44
After updating it works ! but the function to change shield color doesn't work. however the basic shield functionalities work (damage, pass through), it just show up as white color shield. 
Also even when i set item to pass through, arrow still get blocked by the shield this expected?

**Comment by McJty** [comment] 2016-03-25 08:55
Yes I know about the shield color. That's simply not implemented yet in 1.8 and 1.9

Items are a bit funky. It didn't work that well in 1.7.10 either. I have to play a bit more with this. In any case I'll close this now as the original problem has apparently been fixed

**Closed by McJty** 2016-03-25 08:55 UTC
