### ISSUE TITLE
Storage Scanner crash

### ISSUE THREAD

**Issue by Pihrra** [McJty/RFTools#720] opened 2016-08-31 11:22 UTC
I was using a tablet linked to a Storage Scanner for some time without issue. I wanted to add a new Modular Storage so I went to the scanner and the game crashed when I hit the scan button. After that the game keeps crashing each time I start the save. I deleted the scanner with MCEdit to fix it and tried again with a new scanner with the same effect.
I'm using the latest version of RFTools on MC 1.10.2

Crash-report : https://gist.github.com/Pihrra/bcfb8566bd972efb38e0dfb91b3e27f7

**Comment by McJty** [comment] 2016-08-31 11:32
Checking

**Comment by McJty** [comment] 2016-08-31 11:36
What kind of inventories are you handling with the scanner? Anything special?

**Comment by Pihrra** [comment] 2016-08-31 11:37
4 or 5 modular storage and a Drawer Controller (from Storage Drawers)

**Comment by McJty** [comment] 2016-08-31 11:38
What version of Storage Drawers?

**Comment by Pihrra** [comment] 2016-08-31 11:40
The latest on Curse : 1.10.2-3.2.6

**Comment by McJty** [comment] 2016-08-31 11:43
This is very likely a bug in the storage drawers mod but I'm trying to reprodue it locally now to confirm that

**Comment by McJty** [comment] 2016-08-31 11:49
Hmm I cannot reproduce this. Are you sure those are the only inventories nearby? Even things like furnaces or other machines sometimes have inventories.

**Comment by Pihrra** [comment] 2016-08-31 11:57
Sorry I just mentioned those that I stared and used with the scanner. So yes there are a lot of machines from Forestry, Immersive Engineering and Ender IO.
But after looking at the crash report I saw mentioned a Level Emitter. I was using one that was linked to the scanner. So I just now deleted it with MCEdit and now I can scan withtout problem. I then put down a new level emitter and the game crashed again.
The crash-report seems very similar  : https://gist.github.com/Pihrra/27e5f394e497536e61bd6b06b37f5992

**Comment by McJty** [comment] 2016-08-31 11:58
yes, it is hitting the same problem. Well. The issue is that one of the machines in the reach of that scanner is buggy. Problem is finding out which one it is...

**Comment by Pihrra** [comment] 2016-08-31 12:01
I'll try a new test world I'll add the same machines one by one and see.

**Comment by McJty** [comment] 2016-08-31 12:02
Ok, thanks that would be helpful

**Comment by Pihrra** [comment] 2016-08-31 12:52
Ok I found the culprit. It's the "Improved Blast Furnace" from Immersive Engineering.
I tested it in a second test world with just the Improved Blast Furnace, a RFTools Storage Scanner and a level Emitter.

**Comment by McJty** [comment] 2016-08-31 12:53
Ok, time to involve @BlueSunrize in this I guess

**Comment by BluSunrize** [comment] 2016-08-31 12:58
Noted. Will be addressed. Thanks ^^

**Comment by McJty** [comment] 2016-09-05 14:25
This will be fixed in IE release 39 (due in a few days according to reliable sources)

**Closed by McJty** 2016-09-05 14:25 UTC

**Comment by Pihrra** [comment] 2016-09-05 22:57
I can confirm my test worlds now load with release 39. Thank you.
