### ISSUE TITLE
Game crashes when i enter a dimension

### ISSUE THREAD

**Issue by xMrNeverDie** [McJty/RFTools#2021] opened 2020-01-20 15:38 UTC
Hey i have a Problem when i try to enter a dimension its crashes my MC sometimes a can stay like 30 sec in the dimension but then its crashes and tells me "Internal Server Error" I'm playing the mod pack MC.Eternal ver. 1.3. If u need more information just tell me :)

MC Ver.: 1.12.2
Mod Ver.: rftools-1.12-7.72, rftoolsdim-1.12-5.71

LOG:
[latest.log](https://github.com/McJtyMods/RFTools/files/4086871/latest.log)

Crash-Report:
[crash-2020-01-20_16.20.18-client.txt](https://github.com/McJtyMods/RFTools/files/4086873/crash-2020-01-20_16.20.18-client.txt)

**Comment by McJty** [comment] 2020-01-20 15:46
It's crashing in danknull. Please check with them:

Caused by: java.lang.NullPointerException
    at p455w0rd.danknull.network.PacketConfigSync$Handler.handle(PacketConfigSync.java:79)

**Comment by josephcsible** [comment] 2020-01-20 15:49
Yep, and this is also a duplicate of McJtyMods/RFToolsDimensions#277, so I'm closing this one.

**Closed as completed by josephcsible** 2020-01-20 15:49 UTC
