### ISSUE TITLE
Text Module deletion and stacking behaviour with Screen

### ISSUE THREAD

**Issue by Hjaldar** [McJty/RFTools#26] opened 2015-02-02 10:03 UTC
rftools-2.21

When shift-clicked into the first slot in a Screen with no Text Modules, a stack of blank Text Modules becomes a single Text Module, effectively deleting the rest of the stack. Once a Text Module exists within the Screen this behaviour stops happening - the Text Modules stack. I am not sure, however, whether there is anything to be gained by allowing blank Text Modules to stack in the module slots of a  Screen.

P.S. Thanks for the mod :) I'm really enjoying it.

**Comment by McJty** [comment] 2015-02-02 10:17
Thanks for reporting. I will check it out.

**Comment by McJty** [comment] 2015-02-02 10:57
I cannot reproduce this. What version of RFTools are you using?

**Comment by Hjaldar** [comment] 2015-02-03 06:55
rftools-2.21

I just re-confirmed it. I suspect interaction with another mod. I'll have to build a new test pack and see if I can find what is causing it. Will report any useful findings.

**Comment by Hjaldar** [comment] 2015-02-03 07:40
I have re-confirmed this with just:

rftools-2.21.jar (and with rftools-2.21.n49.jar)
CoFH Core 3.0.0B9
Forge 10.13.2.1277 (and 1291)

I suspect my description above may have been ambiguous. The series of steps I used was:

1. Place a screen in the world.
2. Right-click the screen to open its GUI.
3. Hover mouse over a stack of 16 blank (i.e. newly created) Text Modules in my inventory. Hold down shift while left-clicking that stack.
4. The stack leaves my inventory but only a single Text Module appears in the top slot of the Screen's GUI, effectively deleting the other 15 Text Modules.

If you are still unable to reproduce then I have no idea what is going on. Not a big issue anyway

**Comment by McJty** [comment] 2015-02-03 07:42
I will try again but those were the steps that I used as well.

**Comment by McJty** [comment] 2015-02-04 11:20
I added a 'Cannot Reproduce' label to this issue but I will not close it until I know it is fixed

**Comment by Vanir2314** [comment] 2015-03-05 14:23
Just an Update to let you know this bug is still in existance. I can confirm it in Version 2.54 (Using FTB Infinity 1.20, Singleplayer)
It is not only affecting Text modules but every Module that can be stacked.
If there is already a module in the slot, it does first fill that stack up and the next used slot will only get one.
Example: Shiftclicking a stack in an empty screen will add one. Shiftclicking 9 more will result in 10 in there. Another stack (of 16) will fill the first slot to 16 and the second stack will only recieve 1

This is not only true for the monitor, but the environmental controller as well. I assume this bug is the same as #73 

Seems like some kind of error due to the fact that the modules/dimlets can be stacked in the inventory but not in the monitor/controller/scrambler

**Comment by McJty** [comment] 2015-03-06 04:33
This must be some kind of weird mod interaction. I still cannot reproduce this at all. The shift-clicking behaviour is perfect for me. I tried in combination without and with inventory tweaks. At the moment I have no clue what is happening here.

**Comment by Vanir2314** [comment] 2015-03-06 15:22
Trying to figure out which mod is the problem.
Current status: 
Used my usual testing environment, where I could confirm the bug (Infinity 1.20, Singleplayer) and disabled mods in batches. Now down to Cofh Core and RFTools. Bug still there. 
Currently trying to start a vanilla Instance, just having latest 1.7.10 forge, latest cofhcore and latest RFTools.
I cannot confirm the theory about a mod conflict: Bug in a vanilla environment present.

Version details:
RFTools 2.54
CoFHCore 3.0.0RC5-207
Forge 10.13.2.1291

System:
Java 1.8.0_25-b18
Windows 7 build 7601 Testmode 64bit
CPU: i7 950
GPU: AMD Radeon 7970 3GB GDDR5 VRAM

Just incase any of this information proves useful to you (don't see how but who knows :D). If you need me to do anything, run a debug version, send you any logs etc. just contact me, since it seems to be a issue not appearing on every device.

Next test once I get to my laptop is for one using linux as OS and then trying LAN mode as well as a local server.

**Comment by McJty** [comment] 2015-03-06 16:56
BTW, when I shift-click a stack of (for example) 16 text modules in the screen 11 of them will be distributed on the screen inventory and the remaining 5 go to the hotbar if there is room there. If not they go back to the inventory.

**Comment by Vanir2314** [comment] 2015-03-06 17:07
Hmm strange for me that doesn't happen. It just puts one in there and eats the rest, or fills the current filled slots in there and adds one to the next.


As previously mentioned, here are my further investigation results:
Bug reproducable in Linux system:
Ubuntu 14.04
Java 1.7.0_55 (so not a Java 8 Problem)
Intel i5-4210U using integrated graphics

Lan mode doesn't change anything (As I would have guessed)

Local server:
Server is running on my Windows machine.
Bug present in multiplayer (local server and server accessed via lan (Linux)) as well

**Comment by McJty** [comment] 2015-03-06 19:05
I can also reproduce it on infinity server. Still no clue why though.

**Comment by Vanir2314** [comment] 2015-03-06 19:13
Just if I wasn't clear, currently I'm testing with vanilla as well (well, nearly vanilla ofc)

**Comment by McJty** [comment] 2015-03-16 09:32
FINALLY found out what the bug is. Next version (2.62) will hopefully fix this annoying bug.

**Closed by McJty** 2015-03-16 09:32 UTC
Labels: Cannot Reproduce
