### ISSUE TITLE
Offset of Dimensions

### ISSUE THREAD

**Issue by Gideonseymour** [McJty/RFTools#27] opened 2015-02-02 21:37 UTC
In order to improve MystCraft compatibility, would it be possible to add a config option to offset the Dimension IDs? Possibly have them start at Dimension -100, and move back? DIM-100, DIM-101, DIM-102? It would help stop certain crashes we've been having with MystCraft.

**Comment by shadowfacts** [comment] 2015-02-02 22:07
Or just have configurable dimension ids

**Comment by McJty** [comment] 2015-02-03 03:42
In my custom modpack I'm running Mystcraft together with RFTools with no issues at all. What kind of crashes are you getting? The problem is that I have no influence over the id's that I get. I simply request the next available id from Minecraft itself.

**Comment by Gideonseymour** [comment] 2015-02-03 14:23
http://pastebin.com/186SmfJP

**Comment by McJty** [comment] 2015-02-03 14:24
Can you describe exactly how this happens? This shouldn't be possible at all.

**Comment by McJty** [comment] 2015-02-03 14:27
Also is this a server log? When exactly does this occur?

**Comment by McJty** [comment] 2015-02-03 14:45
I think this is probably going to be another issue that has nothing to do with the range of the dimension ID. But I'm need more information.

**Comment by Gideonseymour** [comment] 2015-02-03 15:01
This happens in singleplayer when attempting to create/join a world

**Comment by Gideonseymour** [comment] 2015-02-03 15:04
I haven't experienced this myself, but it happens to certain people in combination with MystCraft

**Comment by progwml6** [comment] 2015-02-03 15:21
From my investigations into these logs last night it looked like a dimension was created with an already existing dim id.

**Comment by McJty** [comment] 2015-02-03 15:24
I think the presence of mystcraft is a coincidence. I think the problem is with RFTools itself. I have a theory but I would need to have more information about this. My theory is there was an earlier crash while trying to generate this dimension and RFTools now has wrong information about what dimensions it manages and what not.

**Comment by Gideonseymour** [comment] 2015-02-03 15:28
This is about all we have. It happens when creating a new world, and then past that, it just keeps crashing that world.

**Comment by McJty** [comment] 2015-02-03 15:28
Can someone describe me the exact steps used to reproduce this problem? i.e. from starting new world, to creating first dimension and so on.

**Comment by McJty** [comment] 2015-02-03 18:17
I'm on irc right now (in #rftools).

Does this happen all the time or only in certain situations? Many people are using RFTools (also in combination with Mystcraft) so I'm very curious about this.

**Comment by McJty** [comment] 2015-02-03 20:05
Thanks to the help of tfox83 I found the issue. I will work on a bug fix and test it further. I could reproduce it by first connecting to a server which had RFTools dimensions and then disconnecting. Then without leaving MC create a new SSP world -> crash. Seems that the dimensions are not properly cleaned up when logging out from a server.

**Comment by McJty** [comment] 2015-02-03 20:05
I will have a fix out by tomorrow

**Comment by Gideonseymour** [comment] 2015-02-03 21:10
\o/

**Comment by McJty** [comment] 2015-02-04 08:33
Should be fixed now. Reopen if it isn't

**Closed by McJty** 2015-02-04 08:33 UTC
