### ISSUE TITLE
Crash with teleporter after breaking/replacing

### ISSUE THREAD

**Issue by sciguyryan** [McJty/RFTools#209] opened 2015-06-14 10:00 UTC
Hey there.

I got the following crash when attempting to use a matter transmitter after breaking and replacing it:

http://pastebin.com/LkXJGTzu

**Comment by McJty** [comment] 2015-06-15 10:14
I cannot reproduce this but I can add code to protect against this happening. However, can you describe in more detail what you did? Did the transmitter have power? Did you put it at the same position? To where was it dialed?

**Comment by sciguyryan** [comment] 2015-06-15 16:40
> Did the transmitter have power?

Yes, before and after.

> Did you put it at the same position?

Yes, before and after.

> To where was it dialed?

It was still in a "dialed" state when placed back down. It was dialing to an existing receiver that was still present after being replaced.

**Comment by McJty** [comment] 2015-06-15 17:33
Well I still cannot reproduce it but I did add a check for this so this crash should not occur in any case. I will close this and hopefully things work out for you in 3.02 (which I'm about to release in a moment)

**Closed by McJty** 2015-06-15 17:33 UTC
Labels: bug
