### ISSUE TITLE
1.12 XNet dependency

### ISSUE THREAD

**Issue by Knito58** [McJty/RFTools#1254] opened 2017-07-01 05:49 UTC
MC 1.12
Forge 14.21.1.2387
RFTools 1.12-6.10beta1
XNet 1.12-1.3.4beta2

https://www.dropbox.com/s/pwein0ye8h409dj/2017-07-01_074108.jpg?dl=1

Text:

RFTools is missing mods it depends on.
Include the following mods or remove RFTools.
xnet 1.3.4 or above

Issue:

According to cursrforge dependencies it should not depend on XNet at all. Works with xnet 1.3.4 though.

**Comment by McJty** [comment] 2017-07-01 05:59
It should not have a hard dependency. I will check out what's going on there

**Comment by McJty** [comment] 2017-07-01 06:05
Can I get the client log for this? Thanks

**Comment by Knito58** [comment] 2017-07-01 07:12
https://www.dropbox.com/s/qxi8hc2n6dzfnl9/fml-client-latest.log?dl=1
latest.log = empty file

**Comment by McJty** [comment] 2017-07-01 07:35
That's the clientlog with XNet. I need to see the clientlog without XNet. The one that is giving errors

**Comment by Knito58** [comment] 2017-07-01 07:52
This one gives the error. The XNet 1.12-1.3.4beta2 evaluates as 1.3.0
With a dot "." right before the "beta2" it might have worked. But RFTools would still depend on xnet.

**Comment by Knito58** [comment] 2017-07-01 07:52
My wife calls - sorry.

**Comment by McJty** [comment] 2017-07-01 07:55
Aha ok. Well rftools doesn't depend on xnet. The problem is indeed the version. If you just remove xnet it works fine (I have tried that)

**Comment by McJty** [comment] 2017-07-01 08:04
Fixed in upcoming release (1.3.4.2)

**Closed by McJty** 2017-07-01 08:04 UTC

**Comment by Knito58** [comment] 2017-07-01 09:33
Thank you.
