### ISSUE TITLE
1.9.4 Crash when viewing achievements

### ISSUE THREAD

**Issue by Peach774** [McJty/RFTools#571] opened 2016-06-17 17:02 UTC
If you view the achievements screen and then drag the screen around to try and find the achievements that don't exist, the game crashes: 

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at net.minecraft.client.gui.achievement.GuiAchievements.func_146552_b(GuiAchievements.java:311)
	at net.minecraft.client.gui.achievement.GuiAchievements.func_73863_a(GuiAchievements.java:204)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:355)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1095)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by McJty** [comment] 2016-06-17 17:55
What version of RFTools? And how is this even related to RFTools?

**Comment by McJty** [comment] 2016-06-17 17:55
I mean I don't do achievements in RFTools for 1.9.4 yet. So I don't see how this can be caused by rftools?

**Comment by Peach774** [comment] 2016-06-17 18:24
There is an rftools achievement page. I don't know why but there is.

**Comment by Peach774** [comment] 2016-06-17 18:25
Also, the newest version for 1.9.4

**Comment by McJty** [comment] 2016-06-17 19:20
I will check it out

**Comment by tyler489** [comment] 2016-06-18 01:24
Just put one achievement on the page or remove the page for now

**Comment by McJty** [comment] 2016-06-20 09:21
I'm fixing the achievements like how they were in 1.7.10. Will be in next release

**Closed by McJty** 2016-06-20 09:21 UTC
