### ISSUE TITLE
Crash when opening in-game manual 

### ISSUE THREAD

**Issue by twoworlds** [McJty/RFTools#1541] opened 2018-01-01 14:05 UTC
MC 1.12.2
Forge 14.23.1.2565
rftools 7.22
mcjtylib 2.6.1

I tried to open the in-game manual of the rftools coal generator.

This gave me this crash:

https://pastebin.com/LncDdcNV

**Comment by McJty** [comment] 2018-01-08 12:38
I cannot reproduce this. @josephcsible this is the second time this has been reported. Do you have any clue what might cause this?

**Comment by josephcsible** [comment] 2018-01-08 12:43
@twoworlds Can you post the whole log? I think there might be something important happening before the actual crash.

@McJty what was the other issue where this happened?

**Comment by McJty** [comment] 2018-01-08 12:45
Hmm. I think the other was reported to me using another way (discord or so)

**Comment by twoworlds** [comment] 2018-01-08 12:47
I don't have the logs any more, but I will try to reproduce!

**Comment by josephcsible** [comment] 2018-01-08 12:48
@twoworlds Also, try temporarily changing your in-game language from de-DE to en-US. If that makes the crash stop happening, then I think I know what the problem is.

**Comment by twoworlds** [comment] 2018-01-08 12:49
@josephcsible I will try and report back!

**Comment by twoworlds** [comment] 2018-01-08 14:02
This is the crashlog:

https://pastebin.com/Fe0AdE89

When switchin the language to en-US ist works, so it has to be a problem with the different localisation.

**Comment by josephcsible** [comment] 2018-01-08 22:31
Should be fixed in the next release of McJtyLib.

**Closed by josephcsible** 2018-01-08 22:31 UTC
