### ISSUE TITLE
[1.8.9] Client crash in creative inventory

### ISSUE THREAD

**Issue by phit** [McJty/RFTools#425] opened 2016-01-14 04:13 UTC
crashing when clicking the tab with all items in the creative inventory
[crash-2016-01-14_05.05.45-client.txt](https://github.com/McJty/RFTools/files/89857/crash-2016-01-14_05.05.45-client.txt)

**Comment by McJty** [comment] 2016-01-14 04:25
This looks like an issue with Chisel & Bits. I'll talk to the author

**Comment by AlgorithmX2** [comment] 2016-01-14 04:43
Have you changed your mod's instances recently? possibly removing a mod and adding RF Tools?

**Comment by phit** [comment] 2016-01-14 04:54
yes, but rftools was in the pack from the start and there have been no removals
modpack changelog http://vpaste.net/Hpp02

only thing i could think of is that the server I'm playing on is missing some mods my client has

**Comment by AlgorithmX2** [comment] 2016-01-14 05:37
I was unable to reproduce the crash on my end, could you try with this build?

https://dl.dropboxusercontent.com/u/9117298/cb/api/chiselsandbits-mc1.8.9-v1.8-beta15.jar

**Comment by phit** [comment] 2016-01-14 06:33
seems to work, doesn't crash when clicking anymore and I can see the items but then crash when scrolling down for a bit because of buildcraft, but thats a different issue

thanks for the quick fix! 

i would post a client log but its 40mb, here the crash report just to make sure its not related to your fix 
[crash-2016-01-14_07.19.53-client.txt](https://github.com/McJty/RFTools/files/89931/crash-2016-01-14_07.19.53-client.txt)

**Comment by AlgorithmX2** [comment] 2016-01-14 07:15
Cool, yeah that crash is definitely something different :+1:

**Comment by McJty** [comment] 2016-01-14 07:16
That other crash seems related to BuildCraft. Closing this ticket now.

**Closed by McJty** 2016-01-14 07:16 UTC
