### ISSUE TITLE
Crash when open manual

### ISSUE THREAD

**Issue by joltak** [McJty/RFTools#1572] opened 2018-01-21 10:22 UTC
Hi, i got crash everytime when i try to open the manual.
i'm in 1.12.2 minecraft version and rftools-1.12-7.23.
And my version of forge is forge-14.23.1.2587.

Hope that could be help

The error :
The game crashed whilst updating screen events
The game crashed whilst updating screen events
Error: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

Edit :
here is the complete crash report 👍 https://pastebin.com/Mn0WDCT1

**Comment by josephcsible** [comment] 2018-01-21 17:28
Duplicate of #1541. It will be fixed in the next release of McJtyLib. Until then, you can work around the issue by changing your language back to en-US.

**Closed by josephcsible** 2018-01-21 17:28 UTC
