### ISSUE TITLE
Storage Block won't accept any modules

### ISSUE THREAD

**Issue by kwpugh** [McJty/RFTools#429] opened 2016-01-20 15:13 UTC
I'm using rftools-1.8.9-4.20beta11.jar in SP and MP server.

The slots in the storage block are greyed out and won't accept any of the tier or filter modules.

**Comment by McJty** [comment] 2016-01-20 15:23
Hmm, this works for me. Can you show a screenshot?

**Comment by kwpugh** [comment] 2016-01-20 15:46
![rftools](https://cloud.githubusercontent.com/assets/8809210/12453832/99c298e6-bf5a-11e5-9481-9a418361d4cf.jpg)

**Comment by McJty** [comment] 2016-01-20 18:25
That looks ok: Did you actually try to put a storage module in the top slot? What was that module called?

**Comment by kwpugh** [comment] 2016-01-20 18:28
I tried tier 1, 2, 3 and they won't "take" in any slot.

**Comment by McJty** [comment] 2016-01-20 18:30
That.s really strange. I cannot reproduce this

**Comment by kwpugh** [comment] 2016-01-20 18:40
So, one of my players discovered that you can shift-click the modules into their slots when the GUI is open, but you cannot drag-n-drop them into the slots.

Is that the way they are supposed to work?

**Comment by McJty** [comment] 2016-01-20 19:04
Drag and drop should work too. I'll investigate

**Comment by McJty** [comment] 2016-01-21 04:35
Ok, I can reproduce this now. Will fix soon

**Comment by McJty** [comment] 2016-01-21 07:32
Fixed in next release

**Closed by McJty** 2016-01-21 07:32 UTC
