### ISSUE TITLE
Storage Scanner/Remote Storage crafting table does not trigger Better Questing

### ISSUE THREAD

**Issue by Mohron** [McJty/RFTools#1647] opened 2018-02-20 18:26 UTC
Issue description: 
When manually crafting with the RFTools Storage Scanner or Remote Storage, Better Questing (BQ) "crafting" tasks are not satisfied.

**Relivant Event Handler:**
https://github.com/Funwayguy/StandardQuestingPack/blob/05d7a2263f14e79ce6d975163b700c4c46ec162d/src/main/java/bq_standard/handlers/EventHandler.java#L21-L33

Steps to reproduce: 

- Add BQ and StandardExpansion
- Create a crafting task in a quest
- Craft said item with RFTools (no credit)
- Craft Item with Vanilla Crafting table (credit given)

Versions:
* Minecraft: 1.12.2
* Forge: forge-1.12.2-14.23.2.2618-universal
* McJtyLib: mcjtylib-1.12-2.6.4
* RFTools: rftools-1.12-7.29
* + BetterQuesting-2.5.236
* + StandardExpansion-2.4.134

Possibly incompatible mods: 
Encountered in Forever Stranded: Lost souls

Relevant logs, if any:

**Comment by josephcsible** [comment] 2018-02-20 18:28
Duplicate of #1469

**Closed by josephcsible** 2018-02-20 18:28 UTC

**Comment by Mohron** [comment] 2018-02-20 18:29
Ah my bad, searched for Better Questing specifically, not the event.
