### ISSUE TITLE
rftools crash

### ISSUE THREAD

**Issue by hihihoholalalolo1227** [McJty/RFTools#1488] opened 2017-12-16 15:03 UTC
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from RFTools (rftools)

**Comment by McJty** [comment] 2017-12-16 15:04
I need a full log. Also version numbers and other information. Please. I can't see your computer from here

**Comment by Pythonic-Rainbow** [comment] 2017-12-19 07:42
I believe I have the same problem with this guy.
I will add the information here.

Forge Build:  MC1.11.2  Build 2579
RFTools version:7.15

`Caused by: java.lang.NoClassDefFoundError: li/cil/oc/api/driver/SidedBlock
	at mcjty.rftools.RFTools.init(RFTools.java:185)`

[https://pastebin.com/vfr337Mc](PASTEBIN full log)

**Comment by McJty** [comment] 2017-12-19 07:46
Update Open Computers

**Comment by Pythonic-Rainbow** [comment] 2017-12-19 07:51
I've googled that class too , and all results are pointing to OpenComputers as well
But Forge says it was caused by RFTools so..
Thanks anyway

**Comment by Pythonic-Rainbow** [comment] 2017-12-19 07:53
Hey , but my Open Computers is the latest version

**Comment by McJty** [comment] 2017-12-19 08:00
What version?

**Comment by Pythonic-Rainbow** [comment] 2017-12-19 08:12
1.7.1.79

**Comment by McJty** [comment] 2017-12-19 08:17
Ah ok. The version in rftools fixing this hasn't been released yet. Waiting for Deep Resonance fixes form @josephcsible to do that

**Comment by Pythonic-Rainbow** [comment] 2017-12-19 08:18
okie thank you!

**Comment by josephcsible** [comment] 2017-12-26 19:34
Fixed in 7.16

**Closed by josephcsible** 2017-12-26 19:34 UTC

**Comment by Pythonic-Rainbow** [comment] 2017-12-27 13:01
Thank you!
