### ISSUE TITLE
Tablet not showing gui when right clicked

### ISSUE THREAD

**Issue by RaymondRM1** [McJty/RFTools#2201] opened 2023-12-22 22:01 UTC
Issue description: 
When setting my storage control screen module to my scanner, when I right click to view my gui, nothing happens.

Steps to reproduce: 
Create a modular storage block and upgrade it with a tier 4 storage module.
Create a scanner, power it, place it nearby and set the detection to a range that can see the storage module. You will now see the modular storage block and any contents added.
Create a storage control screen module and a tablet. Set the control screen module to the scanner.
Shift + Right Click to open up tablet GUI and insert storage control screen module.
Point into the air and Right Click. Nothing will happen.

Versions:
* Minecraft: v1.20.1
* NeoForge: v47.1.76
* McJtyLib: v1.20-8.0.3
* RFTools: v1.20-5.0.2

ModPack: Direwolf20 1.20

**Comment by McJty** [comment] 2023-12-23 04:15
Duplicate of https://github.com/McJtyMods/RFToolsStorage/issues/82#issuecomment-1835541642
And also wrong github. RFTools is the old 1.12 mod

**Closed as completed by McJty** 2023-12-23 04:15 UTC

**Comment by boomchekawowow** [comment] 2024-11-12 11:57
Hey, I'm having the same issue. 

I'm playing MeatballCraft ModPack ( Meatballcraft-beta-0.16.05-hotfix1 ) running on MC 1.12.2
we also added Modular Machinery: Community Edition 2.0.3

I'm unable to open GUI to put in the Remote Storage Module.

When I right-click it just spams chat that I don't have anything in the tablet.

I've tried charging it, doesn't change anything.

These are the only 2 crafting recipes I can do.
![image](https://github.com/user-attachments/assets/5d9dcebf-a224-41c8-86de-56b3240c67e6)

**Comment by McJty** [comment] 2024-11-12 12:08
On 1.12.2 you can't do it like that. You have to craft the tablet together with the storage module. So just put it in the crafting grid

**Comment by boomchekawowow** [comment] 2024-11-12 12:15
> On 1.12.2 you can't do it like that. You have to craft the tablet together with the storage module. So just put it in the crafting grid

Sorry added more info above, there's no crafting recipe for it.

**Comment by McJty** [comment] 2024-11-12 12:19
Put empty tablet (has to be empty) on first slot in crafting grid and storage module on second slot. That should do it

**Comment by boomchekawowow** [comment] 2024-11-12 12:22
Not working, I've tried with every module. Also, I'm doing this in a creative world, so outside my server.

![image](https://github.com/user-attachments/assets/c0653769-5f96-422c-8c5e-9c02847aed2d)

**Comment by McJty** [comment] 2024-11-12 12:24
Hmm must be some other mod doing something bad then. No idea. Unfortunatelly I no longer develop or support 1.12.2 anymore so can't really do much

**Comment by boomchekawowow** [comment] 2024-11-12 12:36
The Modpack has Mods that change crafting recipes could it be possible that the recipe was left out?

**Comment by McJty** [comment] 2024-11-12 12:37
yes possibly
