### ISSUE TITLE
Crafter not applying state of the Keep and Int buttons

### ISSUE THREAD

**Issue by nicodon04** [McJty/RFTools#933] opened 2016-12-18 10:09 UTC
Everytime I change one of these buttons

![](https://i.gyazo.com/01d2be3016a72698301d7d094fd493d6.png)

and hit apply, it doesn't save the state, making it impossible to do multistep crafting.

I am on the latest version on Curse, using a custom modpack with RFTools, RFTools Control, RFTools dimensions, and Just Enough Items.

Minecraft version is 1.11.

**Comment by nicodon04** [comment] 2016-12-18 14:12
UPDATE: I tried this in 1.10 too, but it still didnt work.

**Comment by McJty** [comment] 2016-12-18 15:47
You have to select a recipe first, then select these buttons and THEN hit apply. Are you doing that? i.e. these buttons are local for a recipe so selecting a recipe is crucial

**Comment by nicodon04** [comment] 2016-12-21 14:04
Yes, I am.

**Comment by McJty** [comment] 2016-12-21 14:09
Can you describe the exact steps that you're doing one by one? Perhaps with screenshots? I cannot reproduce this and other people are having no issue with this either so I'm trying to find out in what case it goes wrong exactly

**Comment by nicodon04** [comment] 2016-12-21 14:13
Well I just place a crafter down, and select a recipe, put in a recipe, change the Ext button to Int, press apply, go into another recipe and back into the first one, and boom its back in Ext.

Doesn't work in any of the crafters, nor does it work with the other button.

I've tried it in 1.10, and 1.11.

I tried on another PC and it still didn't work.

**Comment by McJty** [comment] 2016-12-21 14:14
To go back to the first recipe you do double click on the recipe?

**Comment by nicodon04** [comment] 2016-12-21 14:15
Yeah

**Comment by McJty** [comment] 2016-12-21 14:21
I still cannot reproduce this. Works perfectly for me. Here is exactly what I do. Make sure to reproduce these steps exactly:

1. Place down new crafter
2. Double click first recipe line
3. Go to JEI and press 'r' on an item with recipe, click that recipe in the crafter
4. Press the 'Ext' button so it becomes 'Int'
5. Hit 'Apply'
6. Double click on line 2: the button goes back to 'Ext'
7. Double click on line 1 again: the button goes back to 'Int'

If this does not work for you then I have no clue at all. You're the first person ever to report this

**Comment by nicodon04** [comment] 2016-12-21 14:25
Nope, still doesn't work.

**Comment by McJty** [comment] 2016-12-21 14:26
Then I give up. Maybe some other mod is messing with this

**Comment by nicodon04** [comment] 2016-12-21 14:26
Unless JEI and Rftools itself can mess with it, I'm pretty sure that isn't the case :P

**Comment by McJty** [comment] 2016-12-21 14:27
BTW, what version of all those mods?

**Comment by nicodon04** [comment] 2016-12-21 14:30
Newest available on Curse. (Custom Profile)

**Comment by McJty** [comment] 2016-12-21 14:30
Can you give me a full log of your minecraft instance running? I'd like to see if there is anything suspicious in there

**Comment by nicodon04** [comment] 2016-12-21 14:32
How would I do that?

**Comment by McJty** [comment] 2016-12-21 14:33
Just get the log (logs folder) and put it on pastebin for example

**Comment by nicodon04** [comment] 2016-12-21 14:34
uuhhh... which file (fml_latest or latest?)

**Comment by McJty** [comment] 2016-12-21 14:35
The one that is the largest

**Comment by nicodon04** [comment] 2016-12-21 14:35
Well, they are all empty, im gonna try running the game again to see if it fills up

**Comment by McJty** [comment] 2016-12-21 14:36
If you didn't run the game then how did you confirm the tests I asked you to do above?

**Comment by nicodon04** [comment] 2016-12-21 14:37
I did run the game, then closed it accidentally

**Comment by nicodon04** [comment] 2016-12-21 14:37
Of all possible times for curse to crash

**Comment by nicodon04** [comment] 2016-12-21 14:40
I am a man of bad luck :P

**Comment by nicodon04** [comment] 2016-12-21 14:43
Here ya go :)
http://pastebin.com/pHNkf2wa

**Comment by McJty** [comment] 2016-12-21 14:47
I have no clue if that's the reason but your java 8 is really old. I wonder if you could try to update that?

**Comment by nicodon04** [comment] 2016-12-21 14:47
It's the latest that it will let me update to!

**Comment by McJty** [comment] 2016-12-21 14:49
Why is that? You have java8 v25. The latest is Java8 v112

**Comment by nicodon04** [comment] 2016-12-21 14:52
Well, the auto updater doesn't show up, and downloading and installing manually (tried two days ago twice) only led to the same result. Why does the official download link contain an incredibly old version?

**Comment by McJty** [comment] 2016-12-21 14:53
No idea

**Comment by perryprog** [comment] 2017-01-11 23:39
Had the same problem, I derped and put the issue [here](https://github.com/raoulvdberge/refinedstorage/issues/857). I fixed it by clicking on a recipe and than clicking Int, but I got a [crash](http://pastebin.com/xzdU6ca5) when recreating the bug on the Tier 2 Crafter.

**Comment by McJty** [comment] 2017-01-12 14:57
The crash will be fixed next version

**Closed by McJty** 2017-01-12 14:57 UTC
Labels: Cannot Reproduce

**Comment by perryprog** [comment] 2017-01-12 16:24
@McJty wow, thank you!
