### ISSUE TITLE
RFTools Crash

### ISSUE THREAD

**Issue by chrislafeken** [McJty/RFTools#340] opened 2015-09-28 00:38 UTC
Currently crashing upon generating a new world or loading an existing one when RFTools is enabled. I'm not sure why, but I'm hoping you can help me so I can use your mod! I love this mod way more than Mystcraft and would much rather enjoy the tech-flavor of the dimension crafting. This is a custom pack I've made for private use on Curse, if a mod list would help i can put it together but I don't have it typed up at the moment.

Extra details that I don't know if matters:
Minecraft version 1.7.10
Forge 10.13.4.1492
AFAIK I'm using the latest version of your mod. I'm not entirely sure because CurseForge seems to pick the version it thinks is best.

Crash report on pastebin:
http://pastebin.com/JStALfd3

I'm not near experienced enough to know why it's not working but it seems to be having a problem with NEI.

Here's another crash report that says something different and to quote one of the lines
 "Caused by: java.lang.ClassNotFoundException: mcjty.rftools.dimension.world.types.ControllerType$BiomeFilter"  :/

2nd Crash report:
http://pastebin.com/jvrf3kAZ

**Comment by McJty** [comment] 2015-09-28 02:55
This is weird. That class is certain present in RFTools. Can it be that your rftools download got corrupted or something?

**Comment by chrislafeken** [comment] 2015-09-28 03:36
I hoped so but I re-downloaded it from Curse again after deletion and it still was crashing. I made sure to test in between deleting and reinstalling the mod that minecraft successfully loaded into the world and was playable. Currenly im rebuilding the private modpack from scratch 4-5 mods at a time AND making a changelog after each try just so i can figure out where the incompatibilities are. Im using Infinity as a base modpack just to get started; so far RFTools is confirmed to work with all the mods in their most updated versions in the modpack. I'm almost positive its one of the obscure mods I've downloaded, but I couldn't narrow it down before. This time hopefully I can and will let you know if I find it : /

**Comment by chrislafeken** [comment] 2015-09-30 23:16
Sorry about posting some more but this is an update. After many versions and trial and error I finally finished the modpack I was making. I put together a changelog which could be useful in maybe determining the problem. At the beginning RFTools obviously worked well with the other mods, and about halfway through I tested it on the server and it was fine with about half the mods in the pack. My method was slow, but I only added in about 4 mods at a time and tested singleplayer creating a new world each time all the way until I am where I am now. My latest version on the changelog you'll see I finished my work and tested it solo style and it worked. HOWEVER, upon adding the last touches to the server and running it, while it starts the server just fine, players can't connect. Unfortunately it still points to RFTools, and I have no idea why : /

But then again, I know almost nothing about this kind of stuff so take that with a grain of salt and all.

Heres the Console's crash log:
http://pastebin.com/xeGKE3tx

Here is my personal changelog I've got going for every change I did start to finish on the modpack. 
http://pastebin.com/F8JZsdHx

I really hope this all helps. Please let me know if you find anything and sorry for so much information.

**Comment by McJty** [comment] 2015-10-01 03:27
Oh:
 [15:56:07] [Client thread/ERROR]: ########## GL ERROR ##########

Seems you have bigger problems then RFTools. Also RFTools is crashing here but it is not the cause of the crash. It is crashing because the setup of something else went wrong. But not should give me the full log. That can contain more information.

**Comment by McJty** [comment] 2015-10-12 10:17
Closing because most likely not an rftools issue. Reopen if you have evidence suggesting otherwise.

**Closed by McJty** 2015-10-12 10:17 UTC
