### ISSUE TITLE
NEI Dissapearing On teleport

### ISSUE THREAD

**Issue by power-spike** [McJty/RFTools#115] opened 2015-03-22 12:45 UTC
Hi, 

When i teleport to a RFTools World, NEI dissapears totally. the Only way to get it back is to go to the title screen, and then go back into the world i was playing. 
Hitting the O key does not bring it back - it is something different. 

This is happening on single player. 

I Am currently playing FTb infinity 1.3, With mekanism 8 (build 526), and rf tools 2.64.

**Comment by McJty** [comment] 2015-03-22 18:19
I cannot reproduce this and have never heard someone else report this. I also have no clue how RFTools could even have an effect on NEI in any way. Can you test if the same happens if you teleport to the nether or to a mystcraft dimension (or the Twilight Forest)?

**Comment by power-spike** [comment] 2015-03-23 23:11
Greetings, 

Sorry i haven't had much time to test this. 

Using the vanilla portal in and out of the nether works fine. 

however nether -> overworld with draconic charm of dislocation induces the error as well. 

I have another issue now, not sure if it's related to this one, if dimension travel to rftools world and back, goto title screen, then load world again - i crash to desktop with server tick loop - error logs report it's in rftools, i'll put in another bug report next time it happens.

**Comment by McJty** [comment] 2015-03-24 04:01
Ok, since the NEI problem is not rftools specific I'm closing this ticket. If you still have the other crash then feel free to make a new ticket for that.

**Closed by McJty** 2015-03-24 04:01 UTC
Labels: Cannot Reproduce
