### ISSUE TITLE
problem with teleportation 

### ISSUE THREAD

**Issue by abdullamu** [McJty/RFTools#103] opened 2015-03-15 20:46 UTC
Good Day
when i teleport from the end to my base in overworld it teleport me to random place with only one chunk loaded it doesnt load anymore and if i use tpx 0 or the portable teleporter it will teleport me but not load the world unless i teleport to other demintion and come back it will lead the world correctly happened after 2.60 i think

**Comment by McJty** [comment] 2015-03-16 04:18
That's very strange. Never heard of this bug and can't reproduce it myself. Can you do some tests and see if this works fine with other teleportation systems (like mystcraft, nether portal, ...)

**Comment by abdullamu** [comment] 2015-03-16 09:00
i use enhanced portals and it seems to teleport me from end to my base just fine but when i use rf tools it always do this and its annoying that i cant use it , i'll try to see and in the console there are nothing wrong no input

**Comment by McJty** [comment] 2015-03-16 09:33
BTW, tpx 0 is not a rftools thing. So if that fails then I think something else is wrong in your setup. But I can't imagine what though.

**Comment by McJty** [comment] 2015-03-20 14:02
Closing due to lack of information and failure to reproduce. Reopen if you have more information about this issue.

**Closed by McJty** 2015-03-20 14:02 UTC
