### ISSUE TITLE
(1.9) Infused shield generator does not work

### ISSUE THREAD

**Issue by LordHellscream** [McJty/RFTools#491] opened 2016-04-02 11:26 UTC
Version (beta37)

When a shield generator is infused (testing 100%, but i think even less than fully infused still have problem), it won't turn the template block into shield when turned on. 
I was testing a tier 3 shield generator, using blue template.
When replaced with non-infused regular tier 3 it works.

**Comment by McJty** [comment] 2016-04-02 16:28
Can you show the full setup? How are you turning it on? Can you give more details? There is no relation at all between being infused and working like that so that should not make a difference

**Comment by LordHellscream** [comment] 2016-04-03 06:03
3x4 wall, 3 blocks tall, with the empty area of 1x2 in the middle. the wall are made of mostly glass blocks, one piece of the wall on the ground level is a shield projector tier 3(100% infused). a coal-generator (100% infused) is next to it.
the empty 1x2 area surrounded by the wall, I then placed 1 piece of blue colored template block, connecting to the shield projector.
Once the shield projector is fully charged, I then use the smart wrench to right-click on the shield generator, the template block then disappears, then I again right-click on the shield generator using the smart wrench, but the template block reappears (instead of the shield). 

I then deleted the shield projector, replace it with a vanilla shield projector without any infusion. Placed it at the exact same spot of where the infused one used to be. I did the same thing (toggling the projector using smart wrench), now the shield appears (instead of the template).

I tried repeat the process, delete the vanilla shield projector, replace it without a infused one. it broke again.
This entire setup is just to test this, I hit this issue while normally playing and i believe then I was just using 25% infused version of a tier 2 shield projector.

**Comment by McJty** [comment] 2016-04-03 06:06
"Once the shield projector is fully charged, I then use the smart wrench to right-click on the shield generator, the template block then disappears, then I again right-click on the shield generator using the smart wrench, but the template block reappears (instead of the shield)."

Well that's normal. The wrench is only to convert the template blocks from shield status and back again. That's not how you turn on the shield.

I totally don't get what is wrong here and I also cannot reproduce this problem at all. But the wrench toggling between template blocks and shield status is normal. Can you show a screenshot perhaps? This report confuses me

**Comment by LordHellscream** [comment] 2016-04-03 06:23
http://imgur.com/NPJQwbE

Simplist set up ever, the middle is a 25% infused coal generator. on the left is a shield projector tier 3 (not infused), on the right is a shield projector tier 3 (25% infused).
All setting to default, both shield gen have hostile damage setting (the only setting).

No redstone involved.

**Comment by Craiel** [comment] 2016-04-20 03:58
Can not reproduce this either with latest RF Tools 1.9 and Forge 12.16.0.1865

http://imgur.com/kckxepo

One thing i noticed was that in your screenshot setup all the power of the Coal Generator would go to only one side first until that block is full, at least with current implementation so there might just not be enough power to run both shields.

**Comment by McJty** [comment] 2016-04-20 04:30
Aha good catch! The coal generator indeed tries to fill one block before it does another. Better use different coal gens for every shield

**Comment by McJty** [comment] 2016-04-22 07:24
Closing. If this is still an issue then let me know and reopen

**Closed by McJty** 2016-04-22 07:24 UTC
