### ISSUE TITLE
[1.12.2][7.24] Elevator or Screens don't work probably

### ISSUE THREAD

**Issue by darkman1984** [McJty/RFTools#1582] opened 2018-01-25 23:35 UTC
Version 7.24

Elevator Screens resets or the Elevator Blocks loosing the Configuration / Connection after leaving and reenter the chunk altough the chunks are loaded through a chunkloader

**Comment by josephcsible** [comment] 2018-01-26 02:46
Can't reproduce. Please provide more details.

**Comment by darkman1984** [comment] 2018-01-26 06:57
I updated yesterday from Version 2.73 to 2.74. In 2.73 the elevator works normally. Since the update sometimes i enter the chunk where the elevator controllers or the screens are and the following happens:

The Screens over the not powered elevator controller show the Read Me. Sometimes when i move forward to the screen, the screen disappear and when i move closer, the screen magically come back :) and shows the ReadMe. Sometimes the Screen is Black
After right clicking the unpowered elevator controller of the floor  the configuration (name) is gone.

The powered elevator controller has also no configuration (name) anymore, so i think the problem depends on the controllers.

First i thought it depends on unloaded chunks but there's a chunkloader from chickenbones.
Tried to fix the problem by replacing the elevator controllers and the screens but that don't work.

If you need more infos and details then easily ask :)

**Comment by josephcsible** [comment] 2018-01-26 12:16
Did you update McJtyLib when you updated RFTools? If not, see if that fixes the issue. Did you change anything else at the same time? What other mods do you have? Can you reproduce the problem with just McJtyLib and RFTools? If not, how about with just them and a chunk loader?

**Comment by josephcsible** [comment] 2018-02-04 04:44
A bug with elevators and screens (though not exactly like this one) was fixed in 7.27. Can you try it there?

**Closed** 2018-02-22 03:51 UTC
Labels: needs response from reporter
