### ISSUE TITLE
Nasty CME when using Builder / Move Mode.

### ISSUE THREAD

**Issue by KaneHart** [McJty/RFTools#204] opened 2015-06-09 10:16 UTC
Was moving a friends base to troll him last night. Worked fine up till I drowned him haha. That was not the issue though there seems to be some sort of list array threading something issue. Anyways here is the report:
http://pastebin.com/HmtprkL7

Funny thing when the server rebooted after the crash it started to revert the process back. It also ended up doing it again sometime after while running.

**Comment by McJty** [comment] 2015-06-09 10:33
Was there an overlap in the source and destination area?

**Comment by KaneHart** [comment] 2015-06-09 10:44
No there was not it was also quite small of an area.

**Comment by McJty** [comment] 2015-06-09 11:41
It wold be nice if you could give me a list of tile entities (machines and stuff) that were in the moved area. Maybe I can reproduce it if I can use one of them myself. I suspect that one of these things is having issues with being moved.

**Comment by McJty** [comment] 2015-06-19 03:33
Closing due to lack of info.

**Closed by McJty** 2015-06-19 03:33 UTC
