### ISSUE TITLE
Peaceful module not working

### ISSUE THREAD

**Issue by permdaddy** [McJty/RFTools#257] opened 2015-07-26 02:03 UTC
on 3.11 SMP

This is the modpack
http://technicpack.net/modpack/modderation-fyad-edition.696257/mods

I had an environmental controller, all the power in the world and mobs were still spawning, despite the range being set to maximum.

**Comment by McJty** [comment] 2015-07-26 03:29
Did you give it enough power (and enough RF/t)? Because with a big range it will need a lot of power (and keep in mind the limits of RF/tick per side of the block). Also what was the actual range? What was the minimum and maximum height and the radius?

**Comment by permdaddy** [comment] 2015-07-26 03:37
It was consuming a little over 6k rf/t and was properly powered(redstone
energy conduit(8k limit) from tesseract being supplied by 4 max size BR
turbines). It didn't seem to work at any range, but I had it with a minimum
of 0, maximum of 180 and a radius of 100.

**Comment by McJty** [comment] 2015-07-26 03:38
What do you mean by not working? What kind of mobs did you see being spawned?

**Comment by permdaddy** [comment] 2015-07-26 03:53
Skeletons, zombies, creepers, witches. At night. I may try and make a dark
room and put the controller right there to test it further, but I saw a ton
of mobs even with it maxxed out.

**Comment by McJty** [comment] 2015-07-26 03:54
Can you show me a screenshot of your setup?

**Comment by permdaddy** [comment] 2015-07-26 04:19
Yeah but it might not be until tomorrow.

**Comment by permdaddy** [comment] 2015-07-26 07:27
Tested in a SP test world.

Creative energy cell. Peaceful Module.

Mobs kept spawning.

Used /cofh killall to reset mobs. They came back.

http://imgur.com/a/Dx9Va

**Comment by McJty** [comment] 2015-07-26 14:22
Ok I will check it out

**Comment by McJty** [comment] 2015-07-27 18:24
I think I know what the problem is. I will fix this for the release of 3.20 tomorrow.

**Comment by McJty** [comment] 2015-07-28 03:41
Fixed in 3.20

**Closed by McJty** 2015-07-28 03:41 UTC
Labels: bug
