### ISSUE TITLE
textures missing

### ISSUE THREAD

**Issue by ternsip** [McJty/RFTools#1201] opened 2017-05-25 08:24 UTC
rftools-1.1x-6.01.jar

[10:17:47] [Client thread/ERROR]: Using missing texture, unable to load rftools:textures/blocks/powercellw.png, java.io.FileNotFoundException
[10:17:47] [Client thread/ERROR]: Using missing texture, unable to load rftools:textures/blocks/powercellu.png, java.io.FileNotFoundException
[10:17:47] [Client thread/ERROR]: Using missing texture, unable to load rftools:textures/blocks/powercells.png, java.io.FileNotFoundException
[10:17:47] [Client thread/ERROR]: Using missing texture, unable to load rftools:textures/blocks/powercelle.png, java.io.FileNotFoundException
[10:17:47] [Client thread/ERROR]: Using missing texture, unable to load rftools:textures/blocks/powercelld.png, java.io.FileNotFoundException
[10:17:47] [Client thread/ERROR]: Using missing texture, unable to load rftools:textures/blocks/powercelln.png, java.io.FileNotFoundException
[10:17:48] [Client thread/ERROR]: Using missing texture, unable to load null:textures/items/verticalHatch.png, java.io.FileNotFoundException

**Comment by josephcsible** [comment] 2018-01-15 03:32
Duplicate of #1102

**Closed by josephcsible** 2018-01-15 03:32 UTC
