### ISSUE TITLE
Screen energy module format resets itself

### ISSUE THREAD

**Issue by mareksipos93** [McJty/RFTools#1911] opened 2019-02-20 20:25 UTC
Issue description:  When Energy Module is used in Screen and that module shows regular RF energy storage - the Format option is not remembered over time and eventually resets itself to default Full format.

Steps to reproduce: 
1. Place Screen
2. Connect it to Screen Controller
2. Bind Energy Module to Energy Pylon from Draconic Core
3. Insert Energy Module to Screen
4. Setup Energy Module to show 'RF' and choose format 'Commas'
5. Play... and when you return after a while format is again 'Full'

Versions:
* Minecraft: 1.12.2
* Forge: 8.0.99.99
* McJtyLib: 1.12-3.0.7
* RFTools: 1.12-7.59

Possibly incompatible mods and versions: none, using only official latest modpack FTB Revelations without any other modifications

Don't know if relevant - but all items were in Chunk Loaded area.

**Comment by Keekuli** [comment] 2019-02-25 22:53
I have same problem, only I have an advanced powercell set to the module and I would like to see the power amount in compact form. 
Minecraft: 1.12.2
Forge: 14.23.5.2781
McJtyLib: 1.12-3.1.1
RFTools: 1.12-7.61

Playing Enigmatica 2 Expert so lots of possible incompatible mods, but I did have the same problem in Stoneblock.

**Comment by Famous5000** [comment] 2019-03-19 15:37
22 days since last update, any progress?
If you need, I can try reproducing this bug with just the mod itself and its dependencies, though I'm pretty sure this is a problem with the mod itself.

**Comment by McJty** [comment] 2019-03-19 18:00
Sorry but I'm in the middle of huge changes so it is hard for me to fix other bugs. I'm afraid this will have to wait for a short while

**Comment by josephcsible** [comment] 2019-03-28 03:31
Fixed as of a614f25

**Closed as completed by josephcsible** 2019-03-28 03:31 UTC
