### ISSUE TITLE
Screen controller crashing server.

### ISSUE THREAD

**Issue by SlothKing16** [McJty/RFTools#1478] opened 2017-12-09 05:30 UTC
I placed a screen and pressed 'scan', it crashed the server immediately, switched over to SP and placed one, hit scan, sure enough my entire client crashed right after. Server starts and crashes shortly after generating the world without having to press 'scan'. SP world will load and only crashes when I hit 'scan'.

Initial server crash: https://pastebin.com/j8dyK9Ex

Crash log after trying to restart server: https://pastebin.com/24mfgNm7

SP Crash log: https://pastebin.com/GrZHdaie

Downgraded RFTools on my SP world and the crash no longer happens. Everytime I click 'scan' it crashes on newest.
The server doesn't last more than 30 seconds before crashing and I don't even get in to click scan.

**Comment by McJty** [comment] 2017-12-09 05:32
You might need to upgrade Open Computers too

**Comment by SlothKing16** [comment] 2017-12-09 05:38
I don't see a version for 1.10.2 that is newer than 1.7.0.124 on curseforge, any idea where I would look?

**Comment by McJty** [comment] 2017-12-09 05:40
Hmm, might be fixed in the version of rftools that I'm about to release in half an hour or so

**Comment by SlothKing16** [comment] 2017-12-09 05:41
Did my crash logs say what was wrong exactly or is it unknown?

**Comment by McJty** [comment] 2017-12-09 05:42
@josephcsible any comments on this? Will your 'modid' merge fix this problem on 1.10?

**Comment by josephcsible** [comment] 2017-12-09 12:55
This is a duplicate of #1466. Bad news is we can't fix this on our end without coremodding or something equally hacky. Good news is that I already got the fix into OC, so it will be in their next release, and [this experimental build](http://ci.cil.li/job/OpenComputers-MC1.10/146/) already contains the fix, for while we're waiting for an official release.

**Closed** 2017-12-09 15:24 UTC
