### ISSUE TITLE
2x2 Screen, buttons on lower half don't work [Bug]

### ISSUE THREAD

**Issue by Sasstraliss** [McJty/RFTools#289] opened 2015-08-13 23:28 UTC
On a 2x2 screen, the buttons on the lower half of the screen don't do anything when you try and click them - no pressing animation or anything.

In fact, I have a button that's placed half on the first half of the screen, and half on the second half. If you click the part of the button in the top half, it works, but not if you click the part of the button on the second half.

Version 3.10, but I don't see anything in the later changelogs that addresses this.

**Comment by McJty** [comment] 2015-08-14 03:22
I cannot reproduce this. They work fine for me. Can you describe the exact steps to reproduce? If you make a new screen and try this again do you have the same problem?

**Comment by McJty** [comment] 2015-08-20 06:33
Closing due to lack of information and unable to reproduce

**Closed by McJty** 2015-08-20 06:33 UTC
