### ISSUE TITLE
Steve's Factory Manager crashes when RFTools >2.40 is installed

### ISSUE THREAD

**Issue by Revemohl** [McJty/RFTools#58] opened 2015-02-23 18:35 UTC
1. Place a Machine Inventory Manager from SFM down
2. Add any of the options that let you set a white of blacklist
3. Try to type anything into the search field in the white/blacklists mentioned above
4. Crash.
This seems to happen even if the only mods you have installed are SFM, RFT and CoFH Core (both the newest and the oldest versions). Tested on Forge 1291.
Going back to version 2.40 fixes this, but anything above that gives the crash.

**Comment by McJty** [comment] 2015-02-23 18:46
Can you provide the cash log?

**Comment by Revemohl** [comment] 2015-02-24 05:08
I forgot to that because of how easy I thought this problem was to reproduce, but after going back to get a crash log I found out that it isn't. Here it is, anyway: http://pastebin.com/3280Kxu1

What I found out is that this problem does not happen on newly created worlds. After some testing, it looks like deleting the RFToolsDimletMapping.dat from a map where this problem happens fixes it, and since I change the contents of my pack all the time I assume this is because some of the IDs present in dimlets.cfg that got converted to the new file aren't there anymore.

So, how safe is it to delete both dimlets.cfg and RFToolsDimletMapping.dat on a world? I haven't made any dimensions yet, but I'd like to be sure.

**Comment by McJty** [comment] 2015-02-24 05:09
If you didn't make any dimensions yet then that should be pretty ok. Thanks for the crash log btw.

**Comment by McJty** [comment] 2015-02-28 19:48
Closing because this is most likely a problem with SFM. Reopen if you can proof that rftools is the cause :-)

**Closed by McJty** 2015-02-28 19:48 UTC

**Comment by Revemohl** [comment] 2015-03-01 08:16
Yeah, the problem went away after deleting the dimlet configs, as said previously. I couldn't figure out exactly whether it happened because of that update that changed how they're saved or because I maybe removed some mod from my pack, but seeing how I tried making new worlds in creative while hopping between versions of RFTools and never got the crash again on those new maps, it's probably the latter.
At least now someone might know what to do in case they run into the same problem.
