### ISSUE TITLE
Versions greater than 2.55 are not compatible with minetweaker

### ISSUE THREAD

**Issue by l3CY** [McJty/RFTools#104] opened 2015-03-15 21:58 UTC
I went to update my modpack today, and after testing I've discovered new versions of RFtools prevent  minetweaker from applying changes.  Immediately on entering a word, I'am my in-game chat box shows [Error executing modifications.zs: null]. 

 There is a way to force changes, but not without consequence. Oddly enough, typing minetwekaers [/mt reload command] does seem to manually apply changes, however this isn't normal behaviour and indicates some sort of compatibility error between RFTools and Minetweaker3.  The consequence of manually enabling the scripts is that any attempt to quit to the main menu and then re open the world are met with State errors which prevent the world from being re opened.  

Below I have provided several images and logs for reference.

This is the complete log.  It includes client startup, world entry, a screenshot, mt/ reload, world exit, attempts to reload the save, and the State errors.
http://pastebin.com/aR27bwbz

This image shows minetweaker failing to load it's changes on save entry.
http://i40.photobucket.com/albums/e230/SlightlyVisible/IMG1_zps3wokm7se.png

**Comment by McJty** [comment] 2015-03-16 04:16
Hmm, strange because latest Pathfinder uses 2.60 and has no problem with Minetweaker... I also don't see how there is anything that I could have done this. Why do you think the problem is with RFTools? I see nothing in the log indicating that?

**Comment by l3CY** [comment] 2015-03-16 21:46
I believe it's related because this issue only occurs when rftools is present.  All probems vanish on either its removal or replacement with 2.55.  If its not on your end, then is it possible minetweaker is at fault for interacting newer versions of rftools incorrectly?  I'm not sure what other information I could provide.  I can easily replicate the problem, but I suppose that isn't helpful if you can't identify it within the log.

**Comment by McJty** [comment] 2015-03-17 04:08
I talked to @Gideonseymour who maintains the FTB Pathfinder mod. He has similar issues but with another mod. I'm guessing that this actually *is* a problem with MineTweaker and I would report it first to them. Gideon got around the issue by forcing /mt reload at startup.

**Comment by McJty** [comment] 2015-03-20 14:01
Closing due to lack of concrete example. Reopen if you have more information related to this.

**Closed by McJty** 2015-03-20 14:01 UTC
