### ISSUE TITLE
Matter Beamer and Spawner manual crashes client

### ISSUE THREAD

**Issue by karrablaster123** [McJty/RFTools#1539] opened 2018-01-01 08:27 UTC
`[13:55:46] [main/ERROR] [mcjty.lib.varia.Logging]: Error reading manual text
java.io.FileNotFoundException: rftools:text/manual-en_gb.txt
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:69) ~[cei.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[cev.class:?]
	at mcjty.lib.gui.widgets.TextPage.setText(TextPage.java:110) ~[TextPage.class:?]
	at mcjty.rftools.items.manual.GuiRFToolsManual.func_73866_w_(GuiRFToolsManual.java:67) ~[GuiRFToolsManual.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478) ~[blk.class:?]
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1016) ~[bib.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:534) ~[FMLClientHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:320) ~[FMLCommonHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:111) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
	at mcjty.rftools.RFTools.openManual(RFTools.java:236) ~[RFTools.class:?]
	at mcjty.lib.gui.GuiSideWindow.help(GuiSideWindow.java:51) ~[GuiSideWindow.class:?]
	at mcjty.lib.gui.GuiSideWindow.lambda$initGui$0(GuiSideWindow.java:38) ~[GuiSideWindow.class:?]
	at mcjty.lib.gui.widgets.Button.fireButtonEvents(Button.java:79) ~[Button.class:?]
	at mcjty.lib.gui.widgets.Button.mouseRelease(Button.java:57) ~[Button.class:?]
	at mcjty.lib.gui.widgets.Panel.mouseRelease(Panel.java:93) ~[Panel.class:?]
	at mcjty.lib.gui.Window.mouseMovedOrUp(Window.java:79) ~[Window.class:?]
	at mcjty.lib.gui.WindowManager.lambda$mouseReleased$9(WindowManager.java:143) ~[WindowManager.class:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_151]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) [?:1.8.0_151]
	at mcjty.lib.gui.WindowManager.mouseReleased(WindowManager.java:143) [WindowManager.class:?]
	at mcjty.lib.container.GenericGuiContainer.func_146286_b(GenericGuiContainer.java:265) [GenericGuiContainer.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543) [blk.class:?]
	at mcjty.lib.container.GenericGuiContainer.func_146274_d(GenericGuiContainer.java:255) [GenericGuiContainer.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501) [blk.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`

Clicking on the ? mark on the right of the GUI to open the manual crashes the game

**Comment by McJty** [comment] 2018-01-01 08:29
More information please! What version of RFTools? What version of Minecraft?

**Comment by karrablaster123** [comment] 2018-01-01 08:33
![untitled](https://user-images.githubusercontent.com/15704074/34466517-84129270-eefc-11e7-8c1b-3a1d8c19027a.png)

Minecraft 1.12.2

**Comment by McJty** [comment] 2018-01-01 08:39
Hmm I cannot reproduce that. What version of McJtyLib?

**Comment by karrablaster123** [comment] 2018-01-01 09:34
Sorry for the late reply. It is version 2.6.1

**Comment by josephcsible** [comment] 2018-01-15 01:04
Same as #1541. Will be fixed in the next version of McJtyLib; until then, the workaround is to use U.S. English as your language.

**Closed by josephcsible** 2018-01-15 01:04 UTC
