### ISSUE TITLE
[Problem] Elevator doesn't go to first floor when you have 3 floors

### ISSUE THREAD

**Issue by Coleres** [McJty/RFTools#641] opened 2016-07-23 09:19 UTC
When i add 3rd floor elevator doesn't go to first floor. When you left-click to button for it, it doesn't do anything however when you press 2nd and 3rd floor there is no problem at all.

**Comment by nikkimas** [comment] 2016-07-28 17:04
is the 3rd Floor button onthe top or on the bottom of the buttons?

**Comment by goldspy98** [comment] 2016-07-30 00:53
I do have a problem like that, however on my tests that is not really an issue of the elevator (maybe of the elevator button tho), when you do have a screen largger than 1 block it won't work as expected, I guess it happens on chunk loaded, the buttons out of the main block (the block where you added the screen) won't response to clicks, that can be fixed by breaking and adding screen again (temp solution) or as a perm solution for now just avoid using screens biggers than 1 block.

Note: I can't confirm this as a mod only issue, I experienced this issue on a bug modpack, I did not really attempted to test it without any other mod installed (I say this because I am using Optifine and well it just break things sometimes).

**Comment by nikkimas** [comment] 2016-07-30 05:36
This is the same problem as stated on #620 (At least I think)

**Comment by Coleres** [comment] 2016-07-31 08:59
As i see, it's not an elevator problem but a screen problem. I used to solve button problem by re arrenging the screen with wrench, however now i can't do that to, it just gives crashes

**Comment by McJty** [comment] 2016-08-01 08:41
Trying to reproduce without success so far

**Comment by McJty** [comment] 2016-08-01 08:58
Fixed next version

**Closed by McJty** 2016-08-01 08:58 UTC
