### ISSUE TITLE
1.15.2 RF Tools Builder CTD

### ISSUE THREAD

**Issue by aetherpirate** [McJty/RFTools#2063] opened 2020-05-21 21:15 UTC
Issue description: 

CTD when clicking to bring up the shape card GUI in the Builder

Steps to reproduce: 

Place Builder, insert Shape Card, click "?" to access GUI 
Versions:
MC 1.15.2
Forge-1.15.2-31.1.74

mcjtylib-1-15-4-1-0-beta.jar
rftoolsbase-1.15-1.1.1-beta.jar
rftoolsbuilder-1.15-2.1.1-beta.jar
rftoolscontrol-1.15-3.0.2-beta.jar
rftoolspower-1-15-2-1-1-beta.jar
rftoolsstorage-1-15-1-1-2-beta.jar
rftoolsutility-1-15-2-1-2-beta.jar

Relevant logs, if any: 
[crash-2020-05-21_17.03.54-client.txt](https://github.com/McJtyMods/RFTools/files/4664821/crash-2020-05-21_17.03.54-client.txt)

**Comment by McJty** [comment] 2020-05-23 08:25
Wrong issue tracker (go to https://github.com/McJtyMods/RFToolsBuilder/issues) and duplicate of
https://github.com/McJtyMods/RFToolsBuilder/issues/18

**Closed as completed by McJty** 2020-05-23 08:25 UTC
