### ISSUE TITLE
Ender Dragon Syringe Unmakable

### ISSUE THREAD

**Issue by austin5919** [McJty/RFTools#255] opened 2015-07-25 06:57 UTC
Started a fresh world in singleplayer. Spawned in some armor, syringes, wings, and an End portal. Took myself OUT of creative mode, went through the portal and flew up to the naturally spawned ender dragon with syringe in hand and left clicked multiple times. Syringe didn't fill up at all, but worked fine later when used on a wither instead. No ERRORS generated either time.

RFTools Version: 3.11
Minecraft Version: 1.7.10
FTB Infinity

**Comment by Divineaspect** [comment] 2015-07-25 15:56
Clarifying Question, are you using any mods which alter the end?

**Comment by austin5919** [comment] 2015-07-25 15:57
It is part of the FTB Infinity pack, so there are some such as Magic Bees and Draconic Evolution.

**Comment by sickhippie** [comment] 2015-07-29 05:34
I'm pretty sure Draconic Evolution modifies the default Ender Dragon specifically so you can spawn new (harder) Ender Dragons with the resurrection ritual.  I can verify that this issue happens on FTB Infinity 1.8.1 with RFTools 3.11 as well.

**Comment by fishmealx** [comment] 2015-09-28 03:56
This is happening on Modsauce 2 as well, which has the Hardcore Ender Expansion, but not Draconic Evolution. Even when we spawn a normal, vanilla dragon with a command the syringe isn't working on it.

**Comment by natedogith1** [comment] 2015-11-04 03:31
This is still an issue. I believe it's caused by the fact that everything you see of the dragon isn't actually an EntityDragon but is rather an EntityDragonPart (which extends Entity not EntityDragon)

**Comment by McJty** [comment] 2015-11-04 04:06
Ah that's a good tip. I will check that out

**Comment by McJty** [comment] 2015-11-17 13:13
Will be fixed in next version

**Closed by McJty** 2015-11-17 13:13 UTC
