### ISSUE TITLE
[1.12.2] Some textures not loading

### ISSUE THREAD

**Issue by twoworlds** [McJty/RFTools#1396] opened 2017-10-09 08:13 UTC
rftools 6.13
mc 1.12.2
forge 14.23.0.2509

I checked my logs today and found this:

[10:02:12] [main/ERROR]: Using missing texture, unable to load rftools:textures/blocks/powercellw.png, java.io.FileNotFoundException
[10:02:12] [main/ERROR]: Using missing texture, unable to load rftools:textures/blocks/powercellu.png, java.io.FileNotFoundException
[10:02:12] [main/ERROR]: Using missing texture, unable to load rftools:textures/blocks/powercells.png, java.io.FileNotFoundException

**Comment by McJty** [comment] 2017-10-09 08:14
yes, known issue but not harmful. In game it looks ok

**Comment by twoworlds** [comment] 2017-10-09 08:15
Wow, that was a quick reply! Thanks for all your work, I really love your mods

**Comment by josephcsible** [comment] 2018-01-15 03:32
Duplicate of #1102

**Closed by josephcsible** 2018-01-15 03:32 UTC
