### ISSUE TITLE
Block protector and inventory items

### ISSUE THREAD

**Issue by PongoSapiens** [McJty/RFTools#1447] opened 2017-11-08 20:09 UTC
This is reopening the issue in #649 and #1113 as it appears to have returned in Minecraft 1.12.2 RFTools 7.13. Specifically sneak right clicking is either ignored or opens the items GUI, which leaves such blocks impossible to select.

**Comment by josephcsible** [comment] 2017-12-31 04:46
I've reopened #1113, so I'm closing this one as a duplicate of it.

**Closed by josephcsible** 2017-12-31 04:46 UTC
