### ISSUE TITLE
[1.12.2] NullPointerException: Exception in server tick loop when trying to create a SP World

### ISSUE THREAD

**Issue by Morpheus1101** [McJty/RFTools#2004] opened 2019-11-28 06:03 UTC
rftools: 7.72
mcjtylib: 3.5.4
Forge: *.2847

To re-create i go into SMP and attempt to go into a liquid world made of molten ender but die to a collapsing world, i then exit SMP, go into SP and when trying to create a world the client crashes with this crash log https://pastebin.com/XMvtBctT

**Comment by josephcsible** [comment] 2019-11-28 06:05
Duplicate of McJtyMods/RFToolsDimensions#205

**Closed as completed by josephcsible** 2019-11-28 06:05 UTC
