### ISSUE TITLE
Screen hit blocks are only created on the client when using third-party wrenches

### ISSUE THREAD

**Issue by maginator** [McJty/RFTools#1698] opened 2018-03-31 16:17 UTC
Hi my Problem is that if i rightclick on a 2x2 or 3x3 Screen they disapear i only can click once and then it is away  

Steps to reproduce: 
Build up a Screen 2x2 or 3x3 and rightclick on a Button Modul or only on the Screen

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.2.2618
* McJtyLib: 6.4
* RFTools: 7.29

Possibly incompatible mods and versions: 
I'm playing FTB Revelation 1.8.0 with Mekanism

**Comment by josephcsible** [comment] 2018-03-31 16:32
Right-clicking a screen with a wrench lets you toggle it being transparent, in addition to changing its size. Is this what you're doing? If so, this is normal behavior. To interact with the screen normally, just use something that's not a wrench. If not, can you upload a video of exactly what you're doing? Further, the versions you gave me don't match what's in Revelation 1.8.0. What changes did you make to your pack?

**Comment by maginator** [comment] 2018-03-31 17:16
Sry My mistake it is Revelation v1.6.0. And I'm using Sphax Texturepack but i think this dosent realy matter. Look at TOP what that say if i rightclick.

![Video](https://user-images.githubusercontent.com/19614585/38165702-d4b16f56-3517-11e8-9e69-99bc993522c5.gif)

**Comment by McJty** [comment] 2018-03-31 17:43
Use an RFTools smart wrench for now. It is a known issue that this doesn't work properly with other wrenches

**Comment by josephcsible** [comment] 2018-03-31 17:44
I'll see if I can get this fixed.

**Comment by maginator** [comment] 2018-03-31 17:57
Ok thank you for the fast help <3

**Comment by josephcsible** [comment] 2018-03-31 19:21
Looks like the problem is in here somewhere:
https://github.com/McJty/RFTools/blob/91126ec9a6eae10436f130276711ed417b7977b7/src/main/java/mcjty/rftools/ForgeEventHandlers.java#L152-L172

**Comment by josephcsible** [comment] 2018-03-31 19:43
Will be fixed in the next release.

**Closed** 2018-03-31 19:43 UTC
