### ISSUE TITLE
Server Crash on removing Shield Projector tier 1

### ISSUE THREAD

**Issue by Bachib** [McJty/RFTools#1724] opened 2018-04-29 15:29 UTC
Issue description:  Upon removing a Shield Projector Tier 1, the server crashed. Does not matter if on or off

Steps to reproduce:   Destroy a Shield Projector Tier 1

Versions:
* Minecraft:  1.12.2      Using FTB Direwolf20 modpack
* Forge:  forge-1.12.2-14.23.2.2611
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:    mcjtylib-1.12-2.6.4
* RFTools:       rftools-1.12-7.29      rftoolsctrl-1.12-1.8.0      rftoolsdim-1.12-5.52

Possibly incompatible mods and versions:  Using Optifine on clientside

Relevant logs, if any: 

Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at mcjty.rftools.blocks.shield.ShieldTEBase.writeClientDataToNBT(ShieldTEBase.java:975)
	at mcjty.lib.entity.GenericTileEntity.func_189518_D_(GenericTileEntity.java:123)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:288)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:250)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

**Comment by Bachib** [comment] 2018-04-29 15:34
Found out it only happens when you remove the Shield Template before removing the Shield Projector

**Comment by josephcsible** [comment] 2018-04-29 16:24
Duplicate of #1645. Has been fixed since version 7.30.

**Closed by josephcsible** 2018-04-29 16:24 UTC
