### ISSUE TITLE
Crashes due to dimlet mapping in world file

### ISSUE THREAD

**Issue by slikrick98** [McJty/RFTools#82] opened 2015-03-02 11:44 UTC
I was playing ftb infinity 1.2.0 (after the server had updated from 1.1.0) and i noticed i was getting this crash here: http://pastebin.com/5mPLWCDC while using the sfm search function. Now at first i thought this was purely an sfm crash but it didnt happen on new worlds nor could i reproduce it. After various testing i boiled it down to rftools and while it was disabled there was no crash. While it was enabled it crashed.

Then i looked into the world file and was going to see the issues and differences between the files and i noticed in data a file named "RFToolsDimletMapping" and after deleting this file and letting it regen as it loaded up the crash was solved. There were no issues after deleting it.

Im not much of a coder, just a bit of a heavy tester but my guess is that the mod removed between pack updates is now leading to a null value and causing the crash. This could be related to other issues with creative crashes people may be having and an update to solve the returned null dimlet or something. If there is any more testing i can do to help let me know, again, not a coder and let me know if there is something im missing or anything else i can do.

**Comment by McJty** [comment] 2015-03-02 11:46
Crashes between SFM and RFTools have been reported before. I don't really have a clue about what is going on and what kind of weird things SFM is doing. I know that for some people updating SFM seemed to have solved things. Not sure if you're already using latest of SFM?

**Comment by slikrick98** [comment] 2015-03-02 11:48
I am indeed using latest SFM. This issue just seems to be from null value that rftools is throwing from a dimlet from a mod that was removed between updates (FTB Infinity 1.1.0 - 1.2.0 if you are interested).

**Comment by McJty** [comment] 2015-03-02 11:50
Yes but the problem is that there is no rftools code anywhere in the stacktrace so I have no idea where that null value would have been returned really.

**Comment by McJty** [comment] 2015-03-02 11:51
Actually I have some ideas. I'm just going to do a few blind fixes for now. There are some spots where I would return null in this case and where I actually do have an alternative.

**Comment by slikrick98** [comment] 2015-03-02 11:51
Yea, the crash does not point to rftools at all, just through my various testing its the only mod having an issue and that specific file being deleted and regenned solved it.

**Comment by slikrick98** [comment] 2015-03-02 11:52
wrong button, woops

**Comment by McJty** [comment] 2015-03-02 11:55
Ok, I implemented a blind fix. There were two cases where a dimlet item would return null in case the thing for which the dimlet was meant no longer exists. That's when getting the name of the item and the icon. I just changed this to return a dummy icon and dummy name. No idea if this will be enough but in next version of RFTools this fix will be included. I'll keep this open for now.

**Comment by portablejim** [comment] 2015-03-02 15:12
That should fix it.

(It was the getUnlocalizedName() returning null. that was the problem this time - found after a long debugging session)

**Comment by McJty** [comment] 2015-03-02 15:15
Ok good to know. Then I will close this item as it will never return null anymore in the next release. Thanks for testing this!

**Closed by McJty** 2015-03-02 15:15 UTC
