### ISSUE TITLE
crash to desktop on world load

### ISSUE THREAD

**Issue by power-spike** [McJty/RFTools#111] opened 2015-03-19 05:16 UTC
it is crashing a few seconds after the dimension finishes building with the error below, i have changed dimlets around a bit - but it's still going down. 

i have broken all the rf tool machines and replaced them as well. 

when i load back up - get the error on the dimension "dimension information missing"

version is FTB Infinity with 2.63 (updated manually) 

in order the dimlets are:- 
Biome extreme hills dimlet -:4
Controller Single Dimlet - :166
Material Ferrous Ore Dimlet - :516
Terrian Flat Dimlet - :407
Time Noon Dimlet - :486

I notcied that the error message says there is no biome controller?

-------------------------- crash log - important part ---------------------
[16:07:09] [Client thread/WARN]: Unable to play unknown soundEvent: minecraft:none
[16:07:13] [Server thread/INFO] [com.mcjty.rftools.RFTools]: id = 105 for TESTbc, descriptor = @BExtreme Hills,CSingle,#mtile.thermalfoundation.ore4,TFlat,tNoon
[16:07:13] [Server thread/INFO] [com.mcjty.rftools.RFTools]:     Base seed: -8406920614826934873
[16:07:13] [Server thread/INFO] [com.mcjty.rftools.RFTools]:     World version: 1
[16:07:13] [Server thread/INFO] [com.mcjty.rftools.RFTools]:     Terrain: TERRAIN_FLAT
[16:07:13] [Server thread/INFO] [com.mcjty.rftools.RFTools]:         Base block: Ferrous Ore
[16:07:13] [Server thread/INFO] [com.mcjty.rftools.RFTools]:         Base fluid: Water
[16:07:13] [Server thread/INFO] [com.mcjty.rftools.RFTools]:     Biome controller: <null>
[16:07:13] [Server thread/INFO] [com.mcjty.rftools.RFTools]:     Biome: Extreme Hills
[16:07:13] [Server thread/INFO] [com.mcjty.rftools.RFTools]:     Sun brightness: 1.0
[16:07:13] [Server thread/INFO] [com.mcjty.rftools.RFTools]:     Star brightness: 1.0
[16:07:13] [Server thread/INFO] [com.mcjty.rftools.RFTools]:     Sky color: 1.0, 1.0, 1.0
[16:07:13] [Server thread/INFO] [com.mcjty.rftools.RFTools]:     Fog color: 1.0, 1.0, 1.0
[16:07:13] [Server thread/INFO] [com.mcjty.rftools.RFTools]:     Sky body: BODY_SUN
[16:07:13] [Server thread/INFO] [com.mcjty.rftools.RFTools]:     Sky body: BODY_REDSUN
[16:07:13] [Server thread/INFO] [com.mcjty.rftools.RFTools]:     Celestial angle: 0.0
[16:07:13] [Server thread/INFO] [com.mcjty.rftools.RFTools]: Sync dimension info to clients!
[16:07:13] [Client thread/INFO] [com.mcjty.rftools.RFTools]: Client side, already registered dimension: 105
[16:07:13] [Client thread/INFO] [STDOUT]: [com.mcjty.rftools.dimension.network.SyncDimensionInfoHelper:syncDimensionManagerFromServer:15]: SYNC DIMENSION STUFF: world.isRemote = true
[16:07:13] [Client thread/INFO] [com.mcjty.rftools.RFTools]: RfToolsDimensionManager.syncFromServer
[16:07:13] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.NullPointerException
	at com.mcjty.rftools.dimension.world.GenericWorldChunkManager.getModdedBiomeGenerators(GenericWorldChunkManager.java:91) ~[GenericWorldChunkManager.class:?]
	at net.minecraft.world.biome.WorldChunkManager.<init>(WorldChunkManager.java:41) ~[aib.class:?]
	at com.mcjty.rftools.dimension.world.GenericWorldChunkManager.<init>(GenericWorldChunkManager.java:26) ~[GenericWorldChunkManager.class:?]
	at com.mcjty.rftools.dimension.world.GenericWorldProvider.setupProviderInfo(GenericWorldProvider.java:88) ~[GenericWorldProvider.class:?]
	at com.mcjty.rftools.dimension.world.GenericWorldProvider.getDimensionInformation(GenericWorldProvider.java:50) ~[GenericWorldProvider.class:?]
	at com.mcjty.rftools.dimension.world.GenericWorldProvider.func_76572_b(GenericWorldProvider.java:73) ~[GenericWorldProvider.class:?]
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:44) ~[aqo.class:?]
	at net.minecraft.world.World.<init>(World.java:244) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97) ~[mt.class:?]
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:14) ~[mm.class:?]
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:245) ~[DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:705) ~[MinecraftServer.class:?]
	at com.mcjty.rftools.dimension.RfToolsDimensionManager.touchSpawnChunk(RfToolsDimensionManager.java:270) ~[RfToolsDimensionManager.class:?]
	at com.mcjty.rftools.dimension.RfToolsDimensionManager.createNewDimension(RfToolsDimensionManager.java:263) ~[RfToolsDimensionManager.class:?]
	at com.mcjty.rftools.blocks.dimlets.DimensionBuilderTileEntity.createDimensionTick(DimensionBuilderTileEntity.java:135) ~[DimensionBuilderTileEntity.class:?]
	at com.mcjty.rftools.blocks.dimlets.DimensionBuilderTileEntity.checkStateServer(DimensionBuilderTileEntity.java:69) ~[DimensionBuilderTileEntity.class:?]
	at com.mcjty.entity.GenericTileEntity.func_145845_h(GenericTileEntity.java:44) ~[GenericTileEntity.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
	... 4 more
[16:07:13] [Server thread/ERROR]: This crash report has been saved to: D:\FTB\FTBInfinity\minecraft\crash-reports\crash-2015-03-19_16.07.13-server.txt
[16:07:13] [Server thread/INFO]: Stopping server
[16:07:13] [Server thread/INFO]: Saving players
[16:07:13] [Server thread/INFO]: Saving worlds
[16:07:13] [Server thread/INFO]: Saving chunks for level 'TS#5'/Overworld
[16:07:13] [Netty Client IO #0/INFO] [THAUMCRAFT]: Restoring client configs.
[16:07:13] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 19/03/15 4:07 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at com.mcjty.rftools.dimension.world.GenericWorldChunkManager.getModdedBiomeGenerators(GenericWorldChunkManager.java:91)
	at net.minecraft.world.biome.WorldChunkManager.<init>(WorldChunkManager.java:41)
	at com.mcjty.rftools.dimension.world.GenericWorldChunkManager.<init>(GenericWorldChunkManager.java:26)
	at com.mcjty.rftools.dimension.world.GenericWorldProvider.setupProviderInfo(GenericWorldProvider.java:88)
	at com.mcjty.rftools.dimension.world.GenericWorldProvider.getDimensionInformation(GenericWorldProvider.java:50)
	at com.mcjty.rftools.dimension.world.GenericWorldProvider.func_76572_b(GenericWorldProvider.java:73)
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:44)
	at net.minecraft.world.World.<init>(World.java:244)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:14)
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:245)
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:705)
	at com.mcjty.rftools.dimension.RfToolsDimensionManager.touchSpawnChunk(RfToolsDimensionManager.java:270)
	at com.mcjty.rftools.dimension.RfToolsDimensionManager.createNewDimension(RfToolsDimensionManager.java:263)
	at com.mcjty.rftools.blocks.dimlets.DimensionBuilderTileEntity.createDimensionTick(DimensionBuilderTileEntity.java:135)
	at com.mcjty.rftools.blocks.dimlets.DimensionBuilderTileEntity.checkStateServer(DimensionBuilderTileEntity.java:69)
	at com.mcjty.entity.GenericTileEntity.func_145845_h(GenericTileEntity.java:44)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.mcjty.rftools.dimension.world.GenericWorldChunkManager.getModdedBiomeGenerators(GenericWorldChunkManager.java:91)
	at net.minecraft.world.biome.WorldChunkManager.<init>(WorldChunkManager.java:41)
	at com.mcjty.rftools.dimension.world.GenericWorldChunkManager.<init>(GenericWorldChunkManager.java:26)
	at com.mcjty.rftools.dimension.world.GenericWorldProvider.setupProviderInfo(GenericWorldProvider.java:88)
	at com.mcjty.rftools.dimension.world.GenericWorldProvider.getDimensionInformation(GenericWorldProvider.java:50)
	at com.mcjty.rftools.dimension.world.GenericWorldProvider.func_76572_b(GenericWorldProvider.java:73)
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:44)
	at net.minecraft.world.World.<init>(World.java:244)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:14)
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:245)
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:705)
	at com.mcjty.rftools.dimension.RfToolsDimensionManager.touchSpawnChunk(RfToolsDimensionManager.java:270)
	at com.mcjty.rftools.dimension.RfToolsDimensionManager.createNewDimension(RfToolsDimensionManager.java:263)
	at com.mcjty.rftools.blocks.dimlets.DimensionBuilderTileEntity.createDimensionTick(DimensionBuilderTileEntity.java:135)
	at com.mcjty.rftools.blocks.dimlets.DimensionBuilderTileEntity.checkStateServer(DimensionBuilderTileEntity.java:69)
	at com.mcjty.entity.GenericTileEntity.func_145845_h(GenericTileEntity.java:44)

-- Block entity being ticked --
Details:
	Name: DimensionBuilderTileEntity // com.mcjty.rftools.blocks.dimlets.DimensionBuilderTileEntity
	Block type: ID #2068 (tile.dimensionBuilderBlock // com.mcjty.rftools.blocks.dimlets.DimensionBuilderBlock)
	Block data value: 8 / 0x8 / 0b1000
	Block location: World: (-655,91,3348), Chunk: (at 1,5,4 in -41,209; contains blocks -656,0,3344 to -641,255,3359), Region: (-2,6; contains chunks -64,192 to -33,223, blocks -1024,0,3072 to -513,255,3583)
	Actual block type: ID #2068 (tile.dimensionBuilderBlock // com.mcjty.rftools.blocks.dimlets.DimensionBuilderBlock)
	Actual block data value: 8 / 0x8 / 0b1000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: TS#5
	All players: 1 total; [EntityPlayerMP['<PROFILE NAME>'/169, l='TS#5', x=-654.65, y=89.00, z=3346.47]]
	Chunk stats: ServerChunkCache: 1024 Drop: 0
	Level seed: -8406920614826934873
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-771,64,1115), Chunk: (at 13,4,11 in -49,69; contains blocks -784,0,1104 to -769,255,1119), Region: (-2,2; contains chunks -64,64 to -33,95, blocks -1024,0,1024 to -513,255,1535)
	Level time: 11508620 game time, 11831516 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 69883 (now: false), thunder time: 13248 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --

**Comment by McJty** [comment] 2015-03-19 05:17
Yes, I'm aware of this bug and fixing it at the moment. In 15 minutes or so a 2.64 should be released with this bugfix.

**Closed by McJty** 2015-03-19 05:17 UTC

**Comment by power-spike** [comment] 2015-03-19 05:31
Great to hear, 

Also crashed after taking out the biome and controller as well.

Let me know if you need any testing done.

**Comment by McJty** [comment] 2015-03-19 05:35
yes, it even crashed without specifying the biome or controller but it was still related to that. I just released 2.64 and I couldn't reproduce the crash anymore. Let me know if that version works for you.

**Comment by power-spike** [comment] 2015-03-23 00:34
So far so good, tested over the w/e, and that crash appears to of been fixed.
