### ISSUE TITLE
[BUG] Inferium Ore Material Dimlet Creating Incorrect Dimension

### ISSUE THREAD

**Issue by SquidSquash** [McJty/RFTools#1498] opened 2017-12-23 00:51 UTC
Playing on AllTheMods3 with RFTools latest 1.12-7.15 version.

Whenever I create a dimension utilising the any of the inferium ore material dimlets from Mystical Aggriculture, the dimension that is created is not using any blocks even from the same mod, for example shown here:

Short 1 min clip, https://youtu.be/8O_VoDp60uI - dimlets + dimension freezes/crashes the game
https://gyazo.com/6907187c10cb463b32ac05fe8fa55ea3 - inside the dimension, the recording stopped before it loaded in, had to screenshot it separately.

With just a simple flat world + inferium ore, I get a world the is generated with Alveary Stabilisers from Forestry...

**Comment by josephcsible** [comment] 2018-01-15 01:11
Duplicate of #1450

**Closed by josephcsible** 2018-01-15 01:11 UTC
