### ISSUE TITLE
Compatibility/fakeplayer issue - Broken elevators -SpongeForge&GriefPrevention

### ISSUE THREAD

**Issue by rob5251** [McJty/RFTools#1601] opened 2018-01-31 01:04 UTC
Since the latest update (7.27) a compatibility issue has occurred where when the RFTools elevator is being used the server will get hung up and time out all players. Once this occurs then the server is stuck in a frozen state.

This issue occurs as soon as the elevator platform is set in motion.
Issue does not occur on previous version (7.26)

When this occurs the last message the server console spits out is this:
`[22:31:49] [Server thread/WARN] [Sponge]: No entity type is registered for class net.minecraftforge.common.util.FakePlayer`

I'm wondering if an error was made in recent changes to: https://github.com/McJty/RFTools/blob/19f938d39f9b1e5abf3200f47e7961f63d112092/src/main/java/mcjty/rftools/blocks/builder/BuilderTileEntity.java

I'm no coder so I wouldn't know, but that's my only guess as the issue only started to occur on the latest version.

I also ran some debug checks with GriefPrevention for SpongeForge but found no apparent issues on their side.

**Comment by josephcsible** [comment] 2018-01-31 01:06
If it doesn't happen without Sponge installed, then it's a Sponge issue and you should report it to them.

**Comment by rob5251** [comment] 2018-01-31 01:11
Will do, just trying to track down the root of the issue. I'll probably just revert to the previous build for now.

**Comment by rob5251** [comment] 2018-02-03 20:57
I tried working through the problem with Blood over on the GriefPrevention issue tracker and he seems to have traced it back to an issue within RFTools:

https://github.com/MinecraftPortCentral/GriefPrevention/issues/587#issuecomment-362841939

**Comment by josephcsible** [comment] 2018-02-04 01:00
Ah, given that information, I was able to reproduce this without Sponge, by using a block protector to protect the platform block immediately in front of the elevator. I'll upload a fix shortly.

**Comment by bloodmc** [comment] 2018-02-04 01:08
@josephcsible Please pass the player interacting with ScreenTileEntity instead of a fakeplayer so GriefPrevention can protect properly.

**Comment by josephcsible** [comment] 2018-02-04 01:08
But the elevator shouldn't consider different blocks to be part of its platform when you call it with redstone versus when you call it with a screen.

**Comment by bloodmc** [comment] 2018-02-04 01:11
The player triggering the move should always be passed in Forge's 'BlockEvent.BreakEvent'. Only use fakeplayer when you have no player. In this case you should always have a player.

**Comment by josephcsible** [comment] 2018-02-04 01:12
It's the elevator that's doing the breaking though, not the player. When a player starts up an RFTools Builder, it's the builder that counts as breaking all of the blocks. Are there any other modded blocks that work this way?

**Comment by bloodmc** [comment] 2018-02-04 01:16
It doesn't matter what block is doing the actual breaking. What matters is what "caused" the block to break. In this case the player that interacted with the ScreenTileEntity caused the elevator to move. And yes plenty of other mods work this way. The ones that do not are doing it wrong.

**Comment by josephcsible** [comment] 2018-02-04 01:40
@bloodmc I disagree, but I'll ask @McJty to have the final say since it is his mod.

@rob5251 This will be fixed in the next release.

**Closed** 2018-02-04 01:39 UTC
Labels: bug

**Comment by rob5251** [comment] 2018-02-04 01:49
Thanks. 👍

**Comment by McJty** [comment] 2018-02-04 04:31
@bloodmc When elevator/builder are activated using a screen I can in principle know the player. However all machines in RFTools can also be operated using redstone logic and machines that procude redstone. In such situations I don't have a player and a fake player is required.
